README.md
after requirements I added an empty line
=> tiny format change

README.md
added using docker without sudo
=> Added Oracle Databes installation link

README.md
1) oracle db link clickable
2) added docker run command insted of in link
3) added grant unlimited tablespace to alanda
4) added installing jdbc drive 7 & 8 manually + download link + install command
5) deleted  create admin user to login -> because unique constraint error
alanda is created automatically
=> READEME.md changes

README.md
changed at the docker run command the ports from 51521:1521 to 1521:1521,
because the port 1521 is deposited in the standalone.xml.
=> README Changed database Port

README.md, backend/alanda-development/src/test/resources/docker-oracle/docker-compose.yml
3 things are open / I am not sure of:
1. adding a short explaination text for/of alanda after the TOC (is there already one somewhere)
2. regading start-dev.sh: npm run start should trigger an install (not sure)
3.  regading start-dev.sh: starting oracle, camunda & elastic together and then doing all the db schema config, elastic index config & deploying the wildfly apps should work?
=> Angular9 readme

frontend/alanda/libs/common/src/lib/components/attachments/attachments.component.ts, frontend/alanda/libs/common/src/lib/components/project-table/project-table.component.ts, frontend/alanda/libs/common/src/lib/components/role-select/role-select.component.ts, frontend/alanda/libs/common/src/lib/components/task-table/task-table.component.ts, frontend/alanda/package-lock.json, frontend/alanda/package.json, frontend/alanda/tslint.json
**Important: There is no rule change**
- Added tslint-angular preset (this combines tslint:recommended + codelyzer)
- Removed custom rules that are exactly the same as from the preset.
- Removed custom rules that are not enforcing something (default false)
=> Improvement: TsLint config follows Angular Styleguide

frontend/alanda/libs/common/src/lib/components/phase-tab/phase-tab.component.ts
=> fix(ang-927): added feedback for phase restart

frontend/alanda/libs/common/src/lib/api/models/comment.ts, frontend/alanda/libs/common/src/lib/components/comments/comments/comments.adapter.ts
=> fix(ang-932): added businesskey tag to comments

backend/alanda-rest-impl/src/main/java/io/alanda/rest/PmcTaskRestService.java, backend/alanda-rest-impl/src/main/java/io/alanda/rest/impl/PmcTaskRestServiceImpl.java, frontend/alanda/libs/common/src/lib/api/taskApi.service.ts
=> fix(ANG-426): added delete task variable restcall

frontend/alanda/libs/common/src/lib/utils/helper-functions.ts
please add new alanda version ANG-965
=> fix(ANG-954): fixed export sperator problem

frontend/alanda/libs/common/src/lib/components/admin/admin.module.ts, frontend/alanda/libs/common/src/lib/components/admin/group-management/group-management.component.html, frontend/alanda/libs/common/src/lib/components/admin/permission-management/permission-management.component.html, frontend/alanda/libs/common/src/lib/components/admin/role-management/role-management.component.html, frontend/alanda/libs/common/src/lib/components/admin/user-management/user-management.component.html, frontend/alanda/libs/common/src/lib/components/attachments/attachments-list/attachments-list.component.html, frontend/alanda/libs/common/src/lib/components/complete-task/complete-task.component.html, frontend/alanda/libs/common/src/lib/components/complete-task/complete-task.module.ts, frontend/alanda/libs/common/src/lib/components/create-project/create-project.component.html, frontend/alanda/libs/common/src/lib/components/create-project/create-project.module.ts, frontend/alanda/libs/common/src/lib/components/milestone-select/milestone-select.component.html, frontend/alanda/libs/common/src/lib/components/milestone-select/milestone-select.module.ts, frontend/alanda/libs/common/src/lib/components/project-and-processes/pap-actions/pap-action-symbol/pap-action-symbol.component.html, frontend/alanda/libs/common/src/lib/components/project-and-processes/pap-config-dialog/pap-config-dialog.component.html, frontend/alanda/libs/common/src/lib/components/project-and-processes/pap-reason-dialog/pap-reason-dialog.component.html, frontend/alanda/libs/common/src/lib/components/project-and-processes/pap-relate-dialog/pap-relate-dialog.component.html, frontend/alanda/libs/common/src/lib/components/project-and-processes/project-and-processes.module.ts, frontend/alanda/libs/common/src/lib/components/project-table/project-table.component.html, frontend/alanda/libs/common/src/lib/components/project-table/project-table.module.ts, frontend/alanda/libs/common/src/lib/components/quick-edit-project-details/quick-edit-project-details.component.html, frontend/alanda/libs/common/src/lib/components/quick-edit-project-details/quick-edit-project-details.module.ts, frontend/alanda/libs/common/src/lib/components/task-table/task-table.component.html, frontend/alanda/libs/common/src/lib/components/task-table/task-table.module.ts, frontend/alanda/libs/common/src/styles/helper.scss
=> style(button): Added Button ripple effect

frontend/alanda/libs/common/src/lib/components/task-table/task-table.component.html, frontend/alanda/libs/common/src/lib/components/task-table/task-table.component.ts
=> refactor(task): Refactored task delegation to rx state

frontend/alanda/libs/common/src/lib/components/history/history-grid.component.html, frontend/alanda/libs/common/src/lib/components/history/history-grid.component.scss, frontend/alanda/libs/common/src/lib/components/history/history-grid.component.ts, frontend/alanda/libs/common/src/lib/components/pio/process-activities/process-activities.component.html, frontend/alanda/libs/common/src/lib/components/pio/process-activities/process-activities.component.scss, frontend/alanda/libs/common/src/lib/components/pio/process-activities/process-activities.component.ts, frontend/alanda/libs/common/src/lib/components/project-and-processes/project-and-processes.component.scss, frontend/alanda/libs/common/src/lib/form/components/prop-checkbox/prop-checkbox.component.html, frontend/alanda/libs/common/src/lib/form/components/prop-select/prop-select.component.html, frontend/alanda/libs/common/src/lib/form/components/var-checkbox/var-checkbox.component.html, frontend/alanda/libs/common/src/lib/form/components/var-datepicker/var-datepicker.component.html, frontend/alanda/libs/common/src/lib/form/components/var-role-user-select/var-role-user-select.component.html, frontend/alanda/libs/common/src/lib/form/components/var-select/var-select.component.html, frontend/alanda/libs/common/src/lib/form/components/var-text/var-text.component.html
=> style(forms): Fixed styles

frontend/alanda/libs/common/src/lib/services/title.service.ts
=> fix(ang-1165): changed window titles

frontend/alanda/libs/common/src/lib/components/date-select/date-select.component.html, frontend/alanda/libs/common/src/lib/components/date-select/date-select.component.ts, frontend/alanda/libs/common/src/lib/components/milestone-select/milestone-select.component.html, frontend/alanda/libs/common/src/lib/components/milestone-select/milestone-select.component.ts, frontend/alanda/libs/common/src/lib/form/components/prop-autocomplete-eager/prop-autocomplete-eager.component.html, frontend/alanda/libs/common/src/lib/form/components/prop-autocomplete-eager/prop-autocomplete-eager.component.ts, frontend/alanda/libs/common/src/lib/form/components/prop-select/prop-select.component.html, frontend/alanda/libs/common/src/lib/form/components/prop-select/prop-select.component.ts, frontend/alanda/libs/common/src/lib/form/components/var-datepicker/var-datepicker.component.html, frontend/alanda/libs/common/src/lib/form/components/var-datepicker/var-datepicker.component.ts, frontend/alanda/libs/common/src/lib/form/components/var-role-user-select/var-role-user-select.component.html, frontend/alanda/libs/common/src/lib/form/components/var-role-user-select/var-role-user-select.component.ts, frontend/alanda/libs/common/src/lib/form/components/var-select/var-select.component.html, frontend/alanda/libs/common/src/lib/form/components/var-select/var-select.component.ts
=> feat(forms): Added prop appendTo

frontend/alanda/libs/common/src/lib/form/components/prop-select/prop-select.component.ts
=> fix(ANG-372): added readonly for prop select

frontend/alanda/libs/common/src/lib/components/milestone-select/milestone-select.component.html, frontend/alanda/libs/common/src/lib/components/milestone-select/milestone-select.component.scss, frontend/alanda/libs/common/src/lib/components/milestone-select/milestone-select.component.ts, frontend/alanda/libs/common/src/lib/components/milestone-select/milestone-select.module.ts
=> feat(milestone-select): Added remove ms option

backend/alanda-rest-impl/src/main/java/io/alanda/rest/document/DocumentRestService.java, backend/alanda-rest-impl/src/main/java/io/alanda/rest/document/DocumentRestServiceImpl.java, frontend/alanda/libs/common/src/lib/api/documentApi.service.ts
=> feat(delete document restcall)

frontend/alanda/libs/common/src/lib/components/task-table/task-table.component.html
https://jira.bpmasters.at/jira/browse/H3ASUPP-2409
=> H3asupp 2409

backend/.gitignore, backend/alanda-base/pom.xml, backend/alanda-base/src/main/java/io/alanda/base/dao/PmcGroupRepo.java, backend/alanda-base/src/main/java/io/alanda/base/dao/PmcUserRepo.java, backend/alanda-base/src/main/java/io/alanda/base/entity/PmcGroup.java, backend/alanda-base/src/main/java/io/alanda/base/entity/PmcUser.java, backend/alanda-base/src/main/java/io/alanda/base/service/PmcUserService.java, backend/alanda-base/src/main/java/io/alanda/base/service/impl/PmcGroupServiceImpl.java, backend/alanda-base/src/main/java/io/alanda/base/service/impl/PmcHistoryServiceImpl.java, backend/alanda-base/src/main/java/io/alanda/base/service/impl/PmcRoleServiceImpl.java, backend/alanda-base/src/main/java/io/alanda/base/service/impl/PmcUserServiceImpl.java, backend/alanda-development/pom.xml, backend/alanda-rest-impl/src/main/java/io/alanda/rest/util/RepoHelpers.java, backend/alanda-rest/pom.xml, backend/alanda-rest/src/main/webapp/WEB-INF/web.xml, backend/pom.xml
=> Angular7 spring upgrade

backend/alanda-base/src/main/java/io/alanda/base/dao/PmcGroupRepo.java, backend/alanda-base/src/main/java/io/alanda/base/dao/PmcUserRepo.java, backend/alanda-base/src/main/java/io/alanda/base/entity/PmcGroup.java, backend/alanda-base/src/main/java/io/alanda/base/service/impl/PmcGroupServiceImpl.java
=> remove unused methods, fix spring-jpa method names

frontend/alanda/libs/common/src/lib/common.module.ts, frontend/alanda/libs/common/src/lib/components/button-badge/button-badge.component.html, frontend/alanda/libs/common/src/lib/components/button-badge/button-badge.component.ts, frontend/alanda/libs/common/src/lib/components/button-badge/button-badge.module.ts
=> H3 apmc 1784

backend/.gitignore, backend/alanda-openapi-mixin/pom.xml, backend/alanda-springboot-mixin/pom.xml, backend/pom.xml, frontend/alanda-libraries/projects/alanda-common/package-lock.json
=> Feature/teamred 17/spring boot mixin

backend/alanda-springboot-mixin/pom.xml, backend/pom.xml
This change adds the possibility to execute intregation test apart from unit tests with the surefire-plugin
TEAMRED-17
=> Feature/teamred 17/build pipeline integration tests

backend/alanda-springboot-mixin/pom.xml, backend/alanda-test-mixin/pom.xml, backend/pom.xml
This mixin will introduce a series of libraries that will enable a potential user to either create Junit4, Junit5 or both tests. It also includes the testcontainers-lib, that allows clients to create integration tests for Wildfly Server applications.
OTA-370
=> Features/ota 146/test libraries mixin

backend/alanda-springboot-mixin/pom.xml
Das Alanda Spring Boot Mixin enthält generische Persistence Lib und Error Handling lib
OTA-146
=> Features/ota 146/added alanda libs to springboot mixin
